"""Protein residue and chemistry constants used across preprocessing/evaluation.

This module modernizes the legacy ``atom_res_dict`` constants by exposing
typed, uppercase module constants while preserving legacy aliases.

`BIAS` is a 3-value model bias vector retained from the original codebase.
Its derivation is not documented in the repository, so values are preserved
verbatim to maintain compatibility with existing scripts/checkpoints.
"""
from __future__ import annotations

from typing import Dict, Tuple

ResidueName = str
AtomName = str
Bond = Tuple[AtomName, AtomName]

RES_ATOM_TYPE_DICT: Dict[ResidueName, list[AtomName]] = {'GLY': ['N', 'CA', 'C', 'O'],
 'CYS': ['N', 'CA', 'C', 'O', 'CB', 'SG'],
 'ARG': ['N', 'CA', 'C', 'O', 'CB', 'CG', 'CD', 'NE', 'CZ', 'NH1', 'NH2'],
 'SER': ['N', 'CA', 'C', 'O', 'CB', 'OG'],
 'THR': ['N', 'CA', 'C', 'O', 'CB', 'OG1', 'CG2'],
 'LYS': ['N', 'CA', 'C', 'O', 'CB', 'CG', 'CD', 'CE', 'NZ'],
 'MET': ['N', 'CA', 'C', 'O', 'CB', 'CG', 'SD', 'CE'],
 'ALA': ['N', 'CA', 'C', 'O', 'CB'],
 'LEU': ['N', 'CA', 'C', 'O', 'CB', 'CG', 'CD1', 'CD2'],
 'ILE': ['N', 'CA', 'C', 'O', 'CB', 'CG1', 'CG2', 'CD1'],
 'VAL': ['N', 'CA', 'C', 'O', 'CB', 'CG1', 'CG2'],
 'ASP': ['N', 'CA', 'C', 'O', 'CB', 'CG', 'OD1', 'OD2'],
 'GLU': ['N', 'CA', 'C', 'O', 'CB', 'CG', 'CD', 'OE1', 'OE2'],
 'HIS': ['N', 'CA', 'C', 'O', 'CB', 'CG', 'ND1', 'CD2', 'CE1', 'NE2'],
 'ASN': ['N', 'CA', 'C', 'O', 'CB', 'CG', 'OD1', 'ND2'],
 'PRO': ['N', 'CA', 'C', 'O', 'CB', 'CG', 'CD'],
 'GLN': ['N', 'CA', 'C', 'O', 'CB', 'CG', 'CD', 'OE1', 'NE2'],
 'PHE': ['N', 'CA', 'C', 'O', 'CB', 'CG', 'CD1', 'CD2', 'CE1', 'CE2', 'CZ'],
 'TRP': ['N', 'CA', 'C', 'O', 'CB', 'CG', 'CD1', 'CD2', 'NE1', 'CE2', 'CE3', 'CZ2', 'CZ3', 'CH2'],
 'TYR': ['N', 'CA', 'C', 'O', 'CB', 'CG', 'CD1', 'CD2', 'CE1', 'CE2', 'CZ', 'OH']}

LABEL_ATOM_TYPE_DICT: Dict[int, set[AtomName]] = {18: {'O', 'N', 'CA', 'C'},
 19: {'C', 'SG', 'O', 'CA', 'CB', 'N'},
 2: {'CZ', 'C', 'NH1', 'NE', 'CG', 'O', 'NH2', 'CA', 'CB', 'CD', 'N'},
 5: {'C', 'O', 'CA', 'CB', 'OG', 'N'},
 6: {'C', 'CG2', 'O', 'CA', 'CB', 'N', 'OG1'},
 1: {'NZ', 'C', 'CG', 'CE', 'O', 'CA', 'CB', 'CD', 'N'},
 13: {'C', 'CG', 'SD', 'O', 'CE', 'CA', 'CB', 'N'},
 9: {'C', 'O', 'CA', 'CB', 'N'},
 11: {'C', 'CG', 'O', 'CD1', 'CA', 'CB', 'CD2', 'N'},
 12: {'C', 'CG2', 'O', 'CD1', 'CA', 'CB', 'CG1', 'N'},
 10: {'C', 'CG2', 'O', 'CA', 'CB', 'CG1', 'N'},
 3: {'C', 'OD2', 'CG', 'O', 'CA', 'CB', 'N', 'OD1'},
 4: {'C', 'CG', 'O', 'CA', 'CB', 'CD', 'OE1', 'OE2', 'N'},
 0: {'C', 'CE1', 'CG', 'NE2', 'O', 'CA', 'CB', 'CD2', 'N', 'ND1'},
 7: {'C', 'ND2', 'CG', 'O', 'CA', 'CB', 'N', 'OD1'},
 17: {'C', 'CG', 'O', 'CA', 'CB', 'CD', 'N'},
 8: {'C', 'CG', 'NE2', 'O', 'CA', 'CB', 'CD', 'OE1', 'N'},
 14: {'CZ', 'C', 'CE1', 'CG', 'O', 'CD1', 'CA', 'CB', 'CE2', 'CD2', 'N'},
 16: {'C', 'CZ2', 'CE3', 'CG', 'O', 'CD1', 'CA', 'CZ3', 'CB', 'CE2', 'CD2', 'CH2', 'N', 'NE1'},
 15: {'CZ', 'C', 'CE1', 'CG', 'O', 'CD1', 'CA', 'CB', 'CE2', 'CD2', 'N', 'OH'}}

RES_GROUP_DICT: Dict[int, str] = {0: 'group1',
 1: 'group1',
 2: 'group1',
 3: 'group2',
 4: 'group2',
 5: 'group3',
 6: 'group3',
 7: 'group3',
 8: 'group3',
 9: 'group4',
 10: 'group4',
 11: 'group4',
 12: 'group4',
 13: 'group4',
 14: 'group5',
 15: 'group5',
 16: 'group5',
 17: 'group6',
 18: 'group6',
 19: 'group7'}

PEPTIDE_BOND_ENERGY: float = 460.0

AA_BOND_DICT: Dict[ResidueName, Dict[Bond, int]] = {'GLY': {('N', 'CA'): 305, ('CA', 'C'): 347, ('C', 'O'): 745},
 'CYS': {('N', 'CA'): 305, ('CA', 'C'): 347, ('C', 'O'): 745, ('CA', 'CB'): 347, ('CB', 'SG'): 259},
 'ARG': {('N', 'CA'): 305,
         ('CA', 'C'): 347,
         ('C', 'O'): 745,
         ('CA', 'CB'): 347,
         ('CB', 'CG'): 347,
         ('CG', 'CD'): 347,
         ('CD', 'NE'): 305,
         ('NE', 'CZ'): 305,
         ('CZ', 'NH1'): 305,
         ('CZ', 'NH2'): 615},
 'SER': {('N', 'CA'): 305, ('CA', 'C'): 347, ('C', 'O'): 745, ('CA', 'CB'): 347, ('CB', 'OG'): 358},
 'THR': {('N', 'CA'): 305,
         ('CA', 'C'): 347,
         ('C', 'O'): 745,
         ('CA', 'CB'): 347,
         ('CB', 'OG1'): 358,
         ('CB', 'CG2'): 347},
 'LYS': {('N', 'CA'): 305,
         ('CA', 'C'): 347,
         ('C', 'O'): 745,
         ('CA', 'CB'): 347,
         ('CB', 'CG'): 347,
         ('CG', 'CD'): 347,
         ('CD', 'CE'): 347,
         ('CE', 'NZ'): 305},
 'MET': {('N', 'CA'): 305,
         ('CA', 'C'): 347,
         ('C', 'O'): 745,
         ('CA', 'CB'): 347,
         ('CB', 'CG'): 347,
         ('CG', 'SD'): 259,
         ('SD', 'CE'): 259},
 'ALA': {('N', 'CA'): 305, ('CA', 'C'): 347, ('C', 'O'): 745, ('CA', 'CB'): 347},
 'LEU': {('N', 'CA'): 305,
         ('CA', 'C'): 347,
         ('C', 'O'): 745,
         ('CA', 'CB'): 347,
         ('CB', 'CG'): 347,
         ('CG', 'CD1'): 347,
         ('CG', 'CD2'): 347},
 'ILE': {('N', 'CA'): 305,
         ('CA', 'C'): 347,
         ('C', 'O'): 745,
         ('CA', 'CB'): 347,
         ('CB', 'CG1'): 347,
         ('CB', 'CG2'): 347,
         ('CG1', 'CD1'): 347},
 'VAL': {('N', 'CA'): 305,
         ('CA', 'C'): 347,
         ('C', 'O'): 745,
         ('CA', 'CB'): 347,
         ('CB', 'CG1'): 347,
         ('CB', 'CG2'): 347},
 'ASP': {('N', 'CA'): 305,
         ('CA', 'C'): 347,
         ('C', 'O'): 745,
         ('CA', 'CB'): 347,
         ('CB', 'CG'): 347,
         ('CG', 'OD1'): 745,
         ('CG', 'OD2'): 358},
 'GLU': {('N', 'CA'): 305,
         ('CA', 'C'): 347,
         ('C', 'O'): 745,
         ('CA', 'CB'): 347,
         ('CB', 'CG'): 347,
         ('CG', 'CD'): 347,
         ('CD', 'OE1'): 745,
         ('CD', 'OE2'): 358},
 'HIS': {('N', 'CA'): 305,
         ('CA', 'C'): 347,
         ('C', 'O'): 745,
         ('CA', 'CB'): 347,
         ('CB', 'CG'): 347,
         ('CG', 'ND1'): 305,
         ('ND1', 'CE1'): 615,
         ('CE1', 'NE2'): 305,
         ('NE2', 'CD2'): 305,
         ('CD2', 'CG'): 614},
 'ASN': {('N', 'CA'): 305,
         ('CA', 'C'): 347,
         ('C', 'O'): 745,
         ('CA', 'CB'): 347,
         ('CB', 'CG'): 347,
         ('CG', 'OD1'): 745,
         ('CG', 'ND2'): 305},
 'PRO': {('N', 'CA'): 305,
         ('CA', 'C'): 347,
         ('C', 'O'): 745,
         ('CA', 'CB'): 347,
         ('CB', 'CG'): 347,
         ('CG', 'CD'): 347,
         ('CD', 'N'): 305},
 'GLN': {('N', 'CA'): 305,
         ('CA', 'C'): 347,
         ('C', 'O'): 745,
         ('CA', 'CB'): 347,
         ('CB', 'CG'): 347,
         ('CG', 'CD'): 347,
         ('CD', 'OE1'): 745,
         ('CD', 'NE2'): 305},
 'PHE': {('N', 'CA'): 305,
         ('CA', 'C'): 347,
         ('C', 'O'): 745,
         ('CA', 'CB'): 347,
         ('CB', 'CG'): 347,
         ('CG', 'CD1'): 614,
         ('CD1', 'CE1'): 347,
         ('CE1', 'CZ'): 614,
         ('CZ', 'CE2'): 347,
         ('CE2', 'CD2'): 614,
         ('CD2', 'CG'): 347},
 'TRP': {('N', 'CA'): 305,
         ('CA', 'C'): 347,
         ('C', 'O'): 745,
         ('CA', 'CB'): 347,
         ('CB', 'CG'): 347,
         ('CG', 'CD1'): 614,
         ('CD1', 'NE1'): 305,
         ('NE1', 'CE2'): 305,
         ('CE2', 'CD2'): 614,
         ('CD2', 'CG'): 305,
         ('CE2', 'CZ2'): 347,
         ('CZ2', 'CH2'): 614,
         ('CH2', 'CZ3'): 347,
         ('CZ3', 'CE3'): 614,
         ('CE3', 'CD2'): 347},
 'TYR': {('N', 'CA'): 305,
         ('CA', 'C'): 347,
         ('C', 'O'): 745,
         ('CA', 'CB'): 347,
         ('CB', 'CG'): 347,
         ('CG', 'CD1'): 614,
         ('CD1', 'CE1'): 347,
         ('CE1', 'CZ'): 614,
         ('CZ', 'OH'): 358,
         ('CZ', 'CE2'): 347,
         ('CE2', 'CD2'): 614,
         ('CD2', 'CG'): 347}}

ABREV: Dict[ResidueName, str] = {'HIS': 'H',
 'LYS': 'K',
 'ARG': 'R',
 'ASP': 'D',
 'GLU': 'E',
 'SER': 'S',
 'THR': 'T',
 'ASN': 'N',
 'GLN': 'Q',
 'ALA': 'A',
 'VAL': 'V',
 'LEU': 'L',
 'ILE': 'I',
 'MET': 'M',
 'PHE': 'F',
 'TYR': 'Y',
 'TRP': 'W',
 'PRO': 'P',
 'GLY': 'G',
 'CYS': 'C'}

LABEL_RES_DICT: Dict[int, ResidueName] = {0: 'HIS',
 1: 'LYS',
 2: 'ARG',
 3: 'ASP',
 4: 'GLU',
 5: 'SER',
 6: 'THR',
 7: 'ASN',
 8: 'GLN',
 9: 'ALA',
 10: 'VAL',
 11: 'LEU',
 12: 'ILE',
 13: 'MET',
 14: 'PHE',
 15: 'TYR',
 16: 'TRP',
 17: 'PRO',
 18: 'GLY',
 19: 'CYS'}

RES_LABEL_DICT: Dict[ResidueName, int] = {'HIS': 0,
 'LYS': 1,
 'ARG': 2,
 'ASP': 3,
 'GLU': 4,
 'SER': 5,
 'THR': 6,
 'ASN': 7,
 'GLN': 8,
 'ALA': 9,
 'VAL': 10,
 'LEU': 11,
 'ILE': 12,
 'MET': 13,
 'PHE': 14,
 'TYR': 15,
 'TRP': 16,
 'PRO': 17,
 'GLY': 18,
 'CYS': 19}

LETTER1_3_DICT: Dict[str, ResidueName] = {'H': 'HIS',
 'K': 'LYS',
 'R': 'ARG',
 'D': 'ASP',
 'E': 'GLU',
 'S': 'SER',
 'T': 'THR',
 'N': 'ASN',
 'Q': 'GLN',
 'A': 'ALA',
 'V': 'VAL',
 'L': 'LEU',
 'I': 'ILE',
 'M': 'MET',
 'F': 'PHE',
 'Y': 'TYR',
 'W': 'TRP',
 'P': 'PRO',
 'G': 'GLY',
 'C': 'CYS'}

BIAS: list[float] = [-0.558, -0.73, 1.226]

# Backwards-compatible aliases for legacy imports.
res_atom_type_dict = RES_ATOM_TYPE_DICT
label_atom_type_dict = LABEL_ATOM_TYPE_DICT
res_group_dict = RES_GROUP_DICT
peptide_bond_energy = PEPTIDE_BOND_ENERGY
AA_bond_dict = AA_BOND_DICT
abrev = ABREV
label_res_dict = LABEL_RES_DICT
res_label_dict = RES_LABEL_DICT
letter1_3_dict = LETTER1_3_DICT
bias = BIAS

__all__ = [
    'RES_ATOM_TYPE_DICT',
    'LABEL_ATOM_TYPE_DICT',
    'RES_GROUP_DICT',
    'PEPTIDE_BOND_ENERGY',
    'AA_BOND_DICT',
    'ABREV',
    'LABEL_RES_DICT',
    'RES_LABEL_DICT',
    'LETTER1_3_DICT',
    'BIAS',
    'res_atom_type_dict',
    'label_atom_type_dict',
    'res_group_dict',
    'peptide_bond_energy',
    'AA_bond_dict',
    'abrev',
    'label_res_dict',
    'res_label_dict',
    'letter1_3_dict',
    'bias',
]
