#!/usr/bin/env python3
"""Train a modern PyTorch 3D CNN on voxel manifests."""

from __future__ import annotations

import argparse
import csv
import json
import random
from dataclasses import asdict
from pathlib import Path
from typing import Any

import numpy as np
import torch
from torch import nn
from torch.optim import AdamW
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm

try:
   from torch import GradScaler           # torch >= 2.3
except ImportError:
   from torch.cuda.amp import GradScaler  # torch < 2.3

from models.cnn3d import CNN3DConfig, VoxelCNN3D, build_loss


class VoxelManifestDataset(Dataset):
    """Dataset backed by a manifest generated by build_voxel_dataset.py."""

    def __init__(self, manifest_path: Path, mean: np.ndarray, std: np.ndarray, task: str):
        self.rows: list[tuple[str, int, int] | tuple[str, int]] = []
        self.manifest_dir = manifest_path.parent.resolve()

        total_rows = None
        with manifest_path.open("r", encoding="utf-8") as count_handle:
            total_lines = sum(1 for _ in count_handle)
            if total_lines > 0:
                total_rows = total_lines - 1

        with manifest_path.open("r", encoding="utf-8", newline="") as handle:
            reader = csv.reader(handle)
            header = next(reader, None)
            if header is not None:
                if "sample_path" in header:
                    idx_path = header.index("sample_path")
                elif "path" in header:
                    idx_path = header.index("path")
                else:
                    raise ValueError("Manifest must contain sample_path (or path) and optional sample_index")

                if "label" not in header:
                    raise ValueError("Manifest must contain sample_path (or path) and optional sample_index")
                idx_label = header.index("label")
                idx_index = header.index("sample_index") if "sample_index" in header else None

                for row in tqdm(reader, total=total_rows, desc="Loading manifest", unit="rows"):
                    if idx_index is not None:
                        self.rows.append((row[idx_path], int(row[idx_index]), int(row[idx_label])))
                    else:
                        self.rows.append((row[idx_path], int(row[idx_label])))

                self.schema = "sharded" if idx_index is not None else "per_example"
            else:
                self.schema = "per_example"

        print(f"Loaded {len(self.rows)} samples from {manifest_path}")
        self.task = task
        self.mean = mean.astype(np.float32)
        self.std = np.maximum(std.astype(np.float32), 1e-6)
        self._cache: dict[Path, np.ndarray | np.lib.npyio.NpzFile] = {}

    def __len__(self) -> int:
        return len(self.rows)

    def _load_file(self, path: Path) -> np.ndarray | np.lib.npyio.NpzFile:
        if not path.is_absolute():
            path = self.manifest_dir / path
        if path not in self._cache:
            self._cache[path] = np.load(path, allow_pickle=False)
        return self._cache[path]

    def __getitem__(self, idx: int) -> tuple[torch.Tensor, torch.Tensor]:
        row = self.rows[idx]
        if self.schema == "sharded":
            sample_path, sample_index, label = row
            sample_obj = self._load_file(Path(sample_path))
            sample = sample_obj[sample_index].astype(np.float32)
        else:
            sample_path, label = row
            sample_obj = self._load_file(Path(sample_path))
            if not isinstance(sample_obj, np.lib.npyio.NpzFile):
                raise ValueError("Per-example schema requires .npz files with 'x' and 'y' arrays")
            sample = sample_obj["x"].astype(np.float32)
            if self.task != "regression" and "y" in sample_obj:
                npz_label = int(np.asarray(sample_obj["y"]).item())
                row_label = int(label)
                if npz_label != row_label:
                    raise ValueError(f"Label mismatch for {sample_path}: manifest={row_label} npz={npz_label}")
        sample = (sample - self.mean) / self.std

        if sample.ndim == 3:
            sample = sample[np.newaxis, ...]
        elif sample.ndim != 4:
            raise ValueError(f"Expected 3D or 4D sample, got shape {sample.shape}")

        x = torch.from_numpy(sample)
        if self.task == "regression":
            y = torch.tensor(float(label), dtype=torch.float32)
        else:
            y = torch.tensor(int(label), dtype=torch.long)
        return x, y


def set_seed(seed: int) -> None:
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)


def run_epoch(
    model: nn.Module,
    loader: DataLoader,
    loss_fn: nn.Module,
    optimizer: torch.optim.Optimizer | None,
    device: torch.device,
    amp_enabled: bool,
    task: str,
    scaler: GradScaler | None = None,
) -> dict[str, float]:
    training = optimizer is not None
    model.train(training)

    total_loss = 0.0
    total_correct = 0
    total_count = 0

    for x, y in loader:
        x = x.to(device)
        y = y.to(device)

        if training:
            optimizer.zero_grad(set_to_none=True)

        with autocast(device_type=device.type, enabled=amp_enabled):
            logits = model(x)
            if task == "regression":
                loss = loss_fn(logits.squeeze(-1), y)
            else:
                loss = loss_fn(logits, y)

        if training:
            if scaler is not None:
                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()
            else:
                loss.backward()
                optimizer.step()

        batch_size = x.shape[0]
        total_loss += loss.item() * batch_size
        total_count += batch_size

        if task != "regression":
            preds = logits.argmax(dim=1)
            total_correct += (preds == y).sum().item()

    metrics = {"loss": total_loss / max(total_count, 1)}
    if task != "regression":
        metrics["accuracy"] = total_correct / max(total_count, 1)
    return metrics


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Train the 3D voxel CNN")
    parser.add_argument("--train-manifest", type=Path, required=True)
    parser.add_argument("--val-manifest", type=Path, required=True)
    parser.add_argument("--normalization", type=Path, required=True)
    parser.add_argument("--output-dir", type=Path, required=True)
    parser.add_argument("--task", choices=["residue_identity", "mutation_activity", "regression"], required=True)
    parser.add_argument("--num-classes", type=int, default=None)
    parser.add_argument("--epochs", type=int, required=True)
    parser.add_argument("--batch-size", type=int, required=True)
    parser.add_argument("--lr", type=float, required=True)

    parser.add_argument("--weight-decay", type=float, default=1e-2)
    parser.add_argument("--dropout", type=float, default=0.5)
    parser.add_argument("--class-weights", choices=["auto", "none"], default="none")
    parser.add_argument("--device", default="cuda" if torch.cuda.is_available() else "cpu")
    parser.add_argument("--num-workers", type=int, default=0)
    parser.add_argument("--amp", action="store_true")
    parser.add_argument("--seed", type=int, default=1337)
    parser.add_argument("--early-stopping-patience", type=int, default=5)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    set_seed(args.seed)

    args.output_dir.mkdir(parents=True, exist_ok=True)
    stats = np.load(args.normalization)
    mean = stats["train_mean"]
    std = stats["train_std"]

    train_ds = VoxelManifestDataset(args.train_manifest, mean=mean, std=std, task=args.task)
    val_ds = VoxelManifestDataset(args.val_manifest, mean=mean, std=std, task=args.task)

    if len(train_ds) == 0:
        raise ValueError("Training manifest is empty")

    input_shape = train_ds[0][0].shape
    in_channels = int(input_shape[0])
    input_size = int(input_shape[-1])

    num_classes = args.num_classes
    if args.task != "regression" and num_classes is None:
        if "class_weights" in stats:
            num_classes = int(len(stats["class_weights"]))
        else:
            raise ValueError("--num-classes is required for classification unless class_weights are in stats")

    config = CNN3DConfig(
        in_channels=in_channels,
        num_classes=num_classes,
        dropout=args.dropout,
        input_size=input_size,
        task=args.task,
    )

    device = torch.device(args.device)
    model = VoxelCNN3D(config).to(device)

    class_weights = None
    if args.class_weights == "auto" and "class_weights" in stats and args.task != "regression":
        class_weights = torch.from_numpy(stats["class_weights"].astype(np.float32)).to(device)

    loss_fn = build_loss(args.task, class_weights=class_weights)
    optimizer = AdamW(model.parameters(), lr=args.lr, weight_decay=args.weight_decay)
    scaler = GradScaler(device=device.type, enabled=args.amp and device.type == "cuda")

    train_loader = DataLoader(
        train_ds,
        batch_size=args.batch_size,
        shuffle=True,
        num_workers=args.num_workers,
        pin_memory=device.type == "cuda",
    )
    val_loader = DataLoader(
        val_ds,
        batch_size=args.batch_size,
        shuffle=False,
        num_workers=args.num_workers,
        pin_memory=device.type == "cuda",
    )

    best_metric = float("inf")
    no_improve = 0
    metrics_log: list[dict[str, Any]] = []

    for epoch in range(1, args.epochs + 1):
        train_metrics = run_epoch(
            model=model,
            loader=train_loader,
            loss_fn=loss_fn,
            optimizer=optimizer,
            device=device,
            amp_enabled=args.amp and device.type == "cuda",
            task=args.task,
            scaler=scaler,
        )
        val_metrics = run_epoch(
            model=model,
            loader=val_loader,
            loss_fn=loss_fn,
            optimizer=None,
            device=device,
            amp_enabled=False,
            task=args.task,
            scaler=None,
        )

        log_entry = {
            "epoch": epoch,
            "train": train_metrics,
            "val": val_metrics,
        }
        metrics_log.append(log_entry)
        print(json.dumps(log_entry))

        monitor = val_metrics["loss"]
        is_best = monitor < best_metric
        if is_best:
            best_metric = monitor
            no_improve = 0
        else:
            no_improve += 1

        checkpoint = {
            "epoch": epoch,
            "model_state": model.state_dict(),
            "optimizer_state": optimizer.state_dict(),
            "config": asdict(config),
            "train_metrics": train_metrics,
            "val_metrics": val_metrics,
            "args": vars(args),
        }
        torch.save(checkpoint, args.output_dir / "last.pt")
        if is_best:
            torch.save(checkpoint, args.output_dir / "best.pt")

        if no_improve >= args.early_stopping_patience:
            print(f"Early stopping at epoch {epoch}")
            break

    with (args.output_dir / "metrics.json").open("w", encoding="utf-8") as handle:
        json.dump(metrics_log, handle, indent=2)


if __name__ == "__main__":
    main()
